name: Url Health Check

on:
  # workflow_dispatch:
  # schedule:
  #   - cron: '30 5 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  url_health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-summer-voice-6058.fly.dev/health
          max-attempts: 3
          retry-delay: 5s
          follow-redirect: true

      - name: Notify success on Discord
        if: success()
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{"title": "Health check OK!", "description": "The health check was successful."}]'
        with:
          args: |
            "✅ Health check OK!"

      - name: Notify failure on Discord
        if: failure()
        uses: Ilshidur/action-discord@0c4b27844ba47cb1c7bee539c8eead5284ce9fa9
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{"title": "Health check failed!", "description": "The health check failed to reach pokedex."}]'
        with:
          args: |
            "❌ Health check failed to reach pokedex."